# Generated by Django 5.2.6 on 2026-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
