# Generated by Django 5.2.6 on 2026-06-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_uploadedfile_extracted_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
